function skillsMember() {
    return [
        'HTML',
        'CSS',
        'JavaScript',
        'React',
        'NodeJs',
        'MongoDB',
        'Express',
        'Python',
        'Django',
        'Flask',
        'Java',
        'Spring',
        'C#',
        'ASP.NET',
        'C++',
        'C',
        'PHP',
        'Laravel',
        'Ruby',
        'Ruby on Rails',
        'Swift',
        'Kotlin',
        'Objective-C',
        'Vue',
        'Angular',
        'SQL',
        'TypeScript',
        'Redux',
        'RESTful API',
        'GraphQL',
        'AWS',
        'Azure',
        'Google Cloud',
        'Docker',
        'Kubernetes',
        'Jenkins',
        'Git',
        'Jira',
        'Confluence',
        'Slack',
        'Trello',
        'Agile',
        'Scrum',
        'Kanban',
        'CI/CD',
        'Microservices',
        'Serverless',
        'PWA',
        'Responsive Design',
        'SEO',
        'UI/UX',
        'Photoshop',
        'Illustrator',
        'Figma',
        'Sketch',
        'Zeplin',
        'InVision',
        'Adobe XD',
        'After Effects',
        'Premiere Pro',
        'Final Cut Pro',
        'DaVinci Resolve',
        '3D Modeling',
        'Blender',
        'Unity',
        'Unreal Engine',
        'AR/VR',
        'IoT',
        'Blockchain',
        'Big Data',
        'Machine Learning',
        'Deep Learning',
        'Artificial Intelligence',
        'Cybersecurity',
        'Ethical Hacking',
        'DevOps',
        'Data Science',
        'Quantum Computing',
        'Robotics',
        'Automation',
        'RPA',
        'NLP',
        'Chatbot',
        'Voice Assistant',
        'Computer Vision',
        'Cloud Computing',
        'Web Development',
        'Mobile Development',
        'Game Development',
        'Desktop Development',
        'Cross-platform Development',
        'Embedded Development',
        'Network Development',
        'Software Development',
        'Frontend Development',
        'Backend Development',
        'Fullstack Development',
        'Web Design',
        'Graphic Design',
        'Motion Design